apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nexacore-secret-provider
  namespace: nexacore
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "dfd7dcec-002d-474a-b282-c17df1dfd6bd"
    keyvaultName: nexacore-kv
    tenantId: "819a2b4e-b175-4249-bb9b-067662f03164"
    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
        - |
          objectName: STRIPE-SECRET-KEY
          objectType: secret
        - |
          objectName: STRIPE-WEBHOOK-SECRET
          objectType: secret
        - |
          objectName: SMTP-HOST
          objectType: secret
        - |
          objectName: SMTP-USER
          objectType: secret
        - |
          objectName: SMTP-PASS
          objectType: secret
  secretObjects:
    - secretName: nexacore-secrets
      type: Opaque
      data:
        - objectName: DB-USER
          key: DB_USER
        - objectName: DB-PASSWORD
          key: DB_PASSWORD
        - objectName: JWT-SECRET
          key: JWT_SECRET
        - objectName: STRIPE-SECRET-KEY
          key: STRIPE_SECRET_KEY
        - objectName: STRIPE-WEBHOOK-SECRET
          key: STRIPE_WEBHOOK_SECRET
        - objectName: SMTP-HOST
          key: SMTP_HOST
        - objectName: SMTP-USER
          key: SMTP_USER
        - objectName: SMTP-PASS
          key: SMTP_PASS