apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: payments-service
  namespace: nexacore
  labels:
    app: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      serviceAccountName: nexacore-sa
      containers:
        - name: payments-service
          image: nexacoreregistry.azurecr.io/payments-service:v1
          ports:
            - containerPort: 3004
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: PORT
              value: "3004"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: NODE_ENV
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: DB_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: DB_NAME_PAYMENTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nexacore-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nexacore-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: nexacore-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nexacore-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: nexacore-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: AUTH_SERVICE_URL
            - name: BILLING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: nexacore-config
                  key: BILLING_SERVICE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
              initialDelaySeconds: 10
              periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
              initialDelaySeconds: 15
              periodSeconds: 20  
  