apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: nexacore
  labels:
    app: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP